### ISSUE TITLE
Getting error on Uploading docs to Elastic search

### ISSUE THREAD

**Issue by ANUDAVIS** [jacopotagliabue/clothes-in-space#2]
def upload_docs_to_es(index_name,docs):
    """
    index_name is a string 
    docs is a map doc id -> doc as a Python dictionary (in our case SKU -> product)
    """
    # first we delete an index with the same name if any 
    # ATTENTION: IF YOU USE THIS CODE IN THE REAL WORLD THIS LINE WILL DELETE THE INDEX
    if es_client.indices.exists(index_name):
        print("Deleting {}".format(index_name))
        es_client.indices.delete(index=index_name)    
    # next we define our index
    body = {
        'settings': {
            "number_of_shards" : 1,
            "number_of_replicas" : 0
        },
        "mappings": {
          "properties": {
                "name": { "type": "text", "analyzer": LANGUAGE },
                "target": { "type": "text", "analyzer": LANGUAGE },
#                "image": { "type": "text", "analyzer": LANGUAGE } ,
                "vector": {
                      "type": "dense_vector",
                      "dims": EMBEDDING_DIMS
                    }
            }
        }
    }
    # create index
    print(body)
  #  print(index_name=ame=ame)
    res = es_client.indices.create(index=index_name, body=body)
    # finally, we bulk upload the documents
    actions = [{
                   "_index": index_name,
                   "_id": sku,
                   "_source": doc
               } for sku, doc in docs.items()
            ]
    # bulk upload
    res = helpers.bulk(es_client, actions)
    
    return res

def query_with_es(index_name, search_query, n=5):
    search_query = {
        "from": 0,
        "size": n,
        "query" : {
            "script_score" : {
                "query": {
                        "match" : {
                            "name" : {
                                "query" : search_query
                            }
                        }
                    },
                "script": {
                  "source" : "doc['popularity'].value / 10"
                }
            }
         }
    }
    res = es_client.search(index=index_name, body=search_query)
    print("Total hits: {}, returned {}\n".format(res['hits']['total']['value'], len(res['hits']['hits'])))
#    return [(hit["_source"]['sku'], hit["_source"]['image']) for hit in res['hits']['hits']]
    return [(hit["_source"]['sku']) for hit in res['hits']['hits']]

def query_and_display_results_with_es(index_name, search_query, n=5):
    res = query_with_es(index_name, search_query, n=n)
    return display_image(res)

def display_image(skus, n=5):
    for (s, image) in skus[:n]:
        print('{} - {}\n'.format(s, image))
        display(Image(image, width=150, unconfined=True))
            
def query_and_rerank_and_display_results_with_es(index_name, search_query, n, session_vector):
    res = query_with_es(index_name, search_query, n=n)
    skus = [r[0] for r in res]
    re_ranked_sku = re_rank_results(session_vector, skus)

    return display_image([(sku, res[skus.index(sku)][1]) for sku in re_ranked_sku])

![CCC](https://user-images.githubusercontent.com/22854116/145024665-fda79d75-52c1-4fb9-87be-4bbc17099cca.png)
![BBB](https://user-images.githubusercontent.com/22854116/145024681-7e654cc7-295b-4530-a912-55f33f27a3e0.png)
![AAA](https://user-images.githubusercontent.com/22854116/145024695-bc4caf2b-4466-4dc8-a2f6-d50be7f908c3.png)

**Comment by jacopotagliabue** [comment]
It seems to be an auth exception, related to connectivity with ES not with the code. Closing as there is nothing to be done on this side!

**Comment by ANUDAVIS** [comment]
thankyou sir every error is solved and everything is working fine now but I
have to change the code in some instances.
Thankyou for your help and support.
