### ISSUE TITLE
Getting error on Uploading docs to Elastic search eventhough connection to Elastic search is done

### ISSUE THREAD

**Issue by ANUDAVIS** [jacopotagliabue/clothes-in-space#3]
INDEX_NAME = 'catalog'  #where index_name is a string. I also want to know whether the 'catalog' here is the catalog file path or what has to be given in this INDEX_NAME.

Got error in below portion of code and Error is given below code portion:
def upload_docs_to_es(index_name,docs):
    """
    index_name is a string 
    docs is a map doc id -> doc as a Python dictionary (in our case SKU -> product)
    """
    #first we delete an index with the same name if any 
    #ATTENTION: IF YOU USE THIS CODE IN THE REAL WORLD THIS LINE WILL DELETE THE INDEX
    if es_client.indices.exists(index_name):
        print("Deleting {}".format(index_name))
        es_client.indices.delete(index=index_name)    
    #next we define our index
    body = {
        'settings': {
            "number_of_shards" : 1,
            "number_of_replicas" : 0
        },
        "mappings": {
          "properties": {
                "name": { "type": "text", "analyzer": LANGUAGE },
                "target": { "type": "text", "analyzer": LANGUAGE },
                "image": { "type": "text", "analyzer": LANGUAGE } ,
                "vector": {
                      "type": "dense_vector",
                      "dims": EMBEDDING_DIMS
                    }
            }
        }
    }
    #create index
    print(body)
    res = es_client.indices.create(index=index_name, body=body)
    #finally, we bulk upload the documents
    actions = [{
                   "_index": index_name,
                   "_id": sku,
                   "_source": doc
               } for sku, doc in docs.items()
            ]
    # bulk upload
    res = helpers.bulk(es_client, actions)
    
    return res

def query_with_es(index_name, search_query, n=5):
    search_query = {
        "from": 0,
        "size": n,
        "query" : {
            "script_score" : {
                "query": {
                        "match" : {
                            "name" : {
                                "query" : search_query
                            }
                        }
                    },
                "script": {
                  "source" : "doc['popularity'].value / 10"
                }
            }
         }
    }
    res = es_client.search(index=index_name, body=search_query)
    print("Total hits: {}, returned {}\n".format(res['hits']['total']['value'], len(res['hits']['hits'])))
   return [(hit["_source"]['sku'], hit["_source"]['image']) for hit in res['hits']['hits']]

def query_and_display_results_with_es(index_name, search_query, n=5):
    res = query_with_es(index_name, search_query, n=n)
    return display_image(res)

def display_image(skus, n=5):
    for (s, image) in skus[:n]:
        print('{} - {}\n'.format(s, image))
        display(Image(image, width=150, unconfined=True))
            
def query_and_rerank_and_display_results_with_es(index_name, search_query, n, session_vector):
    res = query_with_es(index_name, search_query, n=n)
    skus = [r[0] for r in res]
    re_ranked_sku = re_rank_results(session_vector, skus)

    return display_image([(sku, res[skus.index(sku)][1]) for sku in re_ranked_sku])

![DDD](https://user-images.githubusercontent.com/22854116/145026158-bb0c9dfc-9d7b-4b78-a4bd-bdebee41d2c9.png)
![EEE](https://user-images.githubusercontent.com/22854116/145026163-39045927-c2b2-487c-b44a-05e8272db048.png)
![FFF](https://user-images.githubusercontent.com/22854116/145026173-01c26d97-1eea-4f62-a544-1e4a34804f66.png)

**Comment by jacopotagliabue** [comment]
Also in this case we seem to have an auth exception with ES, which depends on the details of your configuration / setup, not so much about the code, whose focus is on product embeddings and re-ranking. Closing as nothing we can do on our side.
