### ISSUE TITLE
Doubt on session.txt file 

### ISSUE THREAD

**Issue by ANUDAVIS** [jacopotagliabue/clothes-in-space#4]
In an e-commerce platform, 
 "sessions.txt is a TAB separated text file storing a session on each line; each session has a numerical id first and then the list of SKUs (matching the content of catalog.csv) that were viewed in that session."
I have a doubt that whether :
1) the session.txt file is text file that is unique and different for different users
or
2) the session.txt file is single file for that e-commerce platform containing skus of products viewed by different users in each session

**Comment by jacopotagliabue** [comment]
sessions.txt is a TAB separated text file that doesn't reflects any industry platform - the actual shape  depends on your use case / platform. Closing this as not relevant to the code.
